import Chat from "@/src/components/chat";
import Sidebar from "@/src/components/sidebar";
import UserNavbar from "@/src/components/user-navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Etendo ChatBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/etendo-favicon.png" />
      </Head>

      <main className="h-screen w-screen">
        <UserNavbar />

        <div className="relative flex h-[90%]">
          <Sidebar />
          <Chat />
        </div>
      </main>
    </>
  );
}
